[control]
prefix = "heisenberg"
outdir = "./fcidump"
save_intergrals = true
integral_format = "fcidump"

[system]
moltype = "1d"
bc = "periodic"
norb = 6
nelec = 6

[model]
hamiltonian = "Heisenberg"
mu = 0.2
J_eq = 1.0
J_ax = 1.0