[control]
prefix = "huckel"
outdir = "./fcidump"
save_intergrals = true
integral_format = "fcidump"

[system]
moltype = "1d"
bc = "periodic"
norb = 6
nelec = 6

[model]
hamiltonian = "Huckel"
basis = "spatial basis"
alpha = 0.5
beta = -1.0
